server:
  port: 4001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 5
      pool-name: HikariCP
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        connection:
          release_mode: on_close
          provider_disables_autocommit: true
    show-sql: true
logging:
  level:
    org.hibernate.type: TRACE
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: staging
---
spring:
  config:
    activate:
      on-profile: prod
